Application:
  Company: "Company"
  Project: "Nav"
  ServiceName: "flm-nav-demo-svc"
  LogLevel: "Debug"
  Env: "Dev"
  Host: "127.0.0.1"
  Port: 10000
Postgresql:
  Host:     ""
  Port     : 5432
  User     : "postgres"
  DbName   : ""
  Password : ""