Application:
  Company: "Company"
  Project: "Nav"
  ServiceName: "flm-nav-demo-svc"
  LogLevel: "Debug"
  Env: "Dev"
  Host: "127.0.0.1"
  Port: 10000
Postgresql:
  Host:     "8.137.119.140"
  Port     : 5432
  User     : "postgres"
  DbName   : "navdemo"
  Password : "Chenhui@123\\!"